version: '2'

services:
  httpd:
    build: ./
    links:
      - maria_db:db
    ports:
      - 8080:80
    volumes:
      - ./server:/var/www/html:Z
  maria_db:
    container_name: maria_db
    image: mariadb:10.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - "3306"
    volumes:
      - ./mariadb:/var/lib/mysql:Z
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - maria_db:db
    ports:
      - 8081:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
